// Generated by ToffeeScript 1.6.3-1
(function() {
  var childproc, globule;

  childproc = require('child_process');

  globule = require('globule');

  exports.process = function(node, tree, cb) {
    var e, err, files, list, out,
      _this = this;
    files = globule.find(node.files);
    list = files.join(' ');
    childproc.exec("uglifyjs " + list + " -o " + node.out, function() {
      e = arguments[0], out = arguments[1], err = arguments[2];
      console.log(out);
      console.log(err);
      return cb(e, out + '\n' + err);
    });
  };

}).call(this);
